### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by RichardLitt** [ralphtheninja/open-funding#57]
Fairly standard practice these days. https://stackoverflow.com/questions/71951105/how-to-change-current-branch-in-git-from-master-to-main

**Comment by matkoniecz** [comment]
I really see no benefit for such changes (and makes as much sense as renaming terminology such as "master's thesis")

**Comment by RichardLitt** [comment]
I would read this. Some people find it offensive, and it costs us nothing to do. https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main

**Comment by matkoniecz** [comment]
> it costs us nothing to do

nothing is far overstating things, unless you value your time at literally zero

and nearly anything is found offensive by someone, usually in inconsistent way (you have cases of people listing master's degrees in their CVs/Linkedins/websites etc being concerned about `master` branch)

**Comment by RichardLitt** [comment]
I hear you.

This is my suggestion - it's just an open issue. This change is one I've made in my repos when I see it, and it's something that other people appreciate. As someone who is a descendant of slavers, I try not to mess around when it comes to someone else letting me know that `master` is an offensive term. I try to listen. I don't mind that it is inconsistent; I'm not making the change for me, but because others have told me it is important to them. That's all I need. So - I saw that our main branch wasn't called main, and I figured it was worth raising.

**Comment by balupton** [comment]
> I try not to mess around when it comes to someone else letting me know that `master` is an offensive term.

To be fair, a word has multiple terms. The slavery term of that word is not the one used here, nor in master thesis. Likewise how it is important to not be offensive, it is also important to steward a responsibility to not be insensibly sensitive; otherwise language is degraded and people's time is wasted. American English makes many such adjustments specific to American sensitivities, irrespective of sensibility, however American English is a minority dialect of the overall english speakers and the international community that GitHub is.

**Comment by vingle** [comment]
There's two issues here:
 - the use of master in 'master thesis', or 'self-mastery', 'master-mind' or 'mastering a musical instrument' is, I think, a different meaning ("a skilled practitioner of a particular art or activity"), to the use within git of being "the leader, in charge, most powerful, boss, dominant, etc". The word in itself isn't imho as problematic as how and where it's used.
 - a public repo can choose to be more inclusive –listening to feedback about use of language & policies– or not. But if not doing so goes against the norms of the platform it's on (every new Githhub/Gitlab project uses 'main' rather than 'master') it may look to newcomers like a deliberate, political statement - even if that's not the intention.

**Comment by balupton** [comment]
> * a public repo can choose to be more inclusive –listening to feedback about use of language & policies– or not. But if not doing so goes against the norms of the platform it's on (every new Githhub/Gitlab project uses 'main' rather than 'master') it may look to newcomers like a deliberate, political statement - even if that's not the intention.

This is about an existing branch, not a new branch. Regardless of what is alleged, edification is a responsibility. It's politics either-way, it includes or excludes either-way. The quoted dichotomy is particularly offensive, that those who do not abide by changing existing branches to be seemingly inclusive of people who allege active and historical racism to invoke a term of a word that was not the term that was used, to defend sensitivity regardless of sensibility, ought to be perceived as political pariahs to newcomers who don't know better. It goes the other way too, that maintainers can choose to assist newcomers to the presupposition of not inferring unjust conclusions based on fallacious conflations, making the overall industry more ultimately inclusive, respectful, and yes, deliberating.

**Comment by vingle** [comment]
> The quoted dichotomy is particularly offensive

I'm sorry, I really didn't mean to offend you.

> that those who do not abide by changing existing branches to be seemingly inclusive of people who allege active and historical racism to invoke a term of a word that was not the term that was used, to defend sensitivity regardless of sensibility, ought to be perceived as political pariahs to newcomers who don't know better

I didn't say that. I seem to have triggered something and really didn't mean to upset you in this way that you feel have to mischaracterize what I said.

I said there's a choice, and maintainers are free to do what they want. FWIW I regularly contribute to a large project that still uses 'master' as the main branch, and I don't think anyone judges them for it - I don't. But someone opened an issue here – one of the project's most active contributors. The context is simply "yes or no" to this specific change, on this specific repo. Some people don't like changing language in response to greater sensitivity and some do… some people also use language changes as a chance to scold/one-up others who still use the old terms, which just bad faiths the whole discussion.

But the idea that a younger, non-Western user of Github who has only ever worked with repos using 'main' as the central branch, one day encounters a project with a 'master' branch _and_ a community pushback against changing that language might judge that project, doesn't seem a wildly opinionated radical idea. I'm obviously not saying the project _should_ or _deserves_ to be judged, just that it might be.

**Comment by matkoniecz** [comment]
> some people also use language changes as a chance to scold/one-up others who still use the old terms, which just bad faiths the whole discussion.

and some people take enthusiasm into finding more and more and more "offensive" words and terms what also sours people on the entire idea and worries some (for example me) what will be the next target

especially people like me who needed to learn English as a foreign language (and have not enjoyed the process at all) are especially unhappy about such changes/redefinitions/deprecations

**Comment by balupton** [comment]
> English is a fluid, regularly evolving language, these kinds of discussions and changes are part of its flexibility

At the hope of informing and at the risk of sounding obtuse, a pedantic note for further clarity is that English is also a divergent language, with distinct evolutionary branches. American English is only one dialect, but is a minority dialect of English internationally, and diverges significantly from the commonwealth and asiatic branches. Recognising and respecting such diversity, such as by reducing Americanisms, improves and includes diversity, which promotes mutual and universal humanisation, which is a superior approach than attempting to heal dehumanisation with appeasement.

Some other examples in American English:
- Oriental is offensive due to it invoking an American guilt of their eastern wars; in the orient however, it is not an offensive term, and people there still use the term to describe themselves
- Western, White, Black, and Privilege are very confusing terms to those outside America, especially for various ethnicities who have grown up in eastern countries, like Singapore, Australia, Hong Kong, Taiwan, Malaysia, Indonesia, Japan; etc whose race and culture have non atomic heritages
- male pronouns are becoming exclusively male in American English, however outside of American English they are still the gender neutral pronouns owing to their inheritance within the mythology imbued within the English language, of which legacy America seems to have failed to inherit within its rapid education and immigration system; this causes plenty of naive and wrong allegations of sexism from Americans to Non American English speakers, including to those of antiquity such as those from the classics and humanities
- American companies always announcing their international products are coming out n Fall, even to an international audience, despite other countries and even to those within the overseas USA states/territories, not always having four seasons nor the same seasons at the same time.

We can see then that it is important to avoid an Americanism of assuming that just because a (prominent) American company or American individual has done or proclaimed something, that it speaks on behalf of all English speakers. Such also leans into a bias of the Big 5 agreeable personality trait, of which inter and intra populations have significant divergences on; and plays a large role in divergent values and politics.

Perhaps there is an assumption that any English repository on GitHub is American and is American English, however that too is an Americanism to be overcome.

**Comment by ralphtheninja** [comment]
Oh wow, I didn't anticipate that much around this :) Anyway, I'm fine with whatever.

**Comment by RichardLitt** [comment]
> Perhaps there is an assumption that any English repository on GitHub is American and is American English, however that too is an Americanism to be overcome.

I didn't bring up American English, and I'm not sure why it matters here. I suspect it was mentioned because I am American, or because some people at GitHub speak it and GitHub itself is legally based in the US. I know multiple staff members at GitHub who don't speak American English natively. I speak American English natively, but having lived in many countries that don't speak it - the UK, Germany, Canada, Antigua, Malta, and now New Zealand - it isn't the only dialect I thought about when suggesting this change. 

> It is also important for one to steward a responsibility to not be insensibly sensitive; otherwise language is degraded and people's time is wasted and edification is spoiled.

I see where you're coming from, but I don't agree with your conclusions. Language will continue to change, and I language degradation isn't anything more than a particular view on that part of that natural process. Prescriptive language changes are neither unusual nor new.

> people like me who needed to learn English as a foreign language (and have not enjoyed the process at all) are likely especially unhappy about such changes/redefinitions/deprecations

I'm sorry that it has been hard, and I understand that Anglophones are considerably privileged in this space. I would also find it annoying to have to relearn the very few Polish words I know, and I have also struggled with some parts of this work - for instance, not saying "guys" to mixed-gender groups. It's hard work. It doesn't always feel useful. Dziękujemy, for speaking in English here with me.  

@ralphtheninja I think it is ultimately your decision. I can't change the name of the main branch.

**Comment by ralphtheninja** [comment]
Let me just ask quickly. Is there anyone _opposed_ to changing the main branch from `master` to `main`?

**Comment by matkoniecz** [comment]
me

**Comment by ralphtheninja** [comment]
New main branch is `main`.

**Comment by RichardLitt** [comment]
Thank you.

**Comment by matkoniecz** [comment]
https://github.com/ralphtheninja/open-funding/branches - `master` branch should be just removed if it was decided to spend effort on renaming master branch?

(I just run into confusing situation as result of having `main` in addition to `master`)

**Comment by ralphtheninja** [comment]
> https://github.com/ralphtheninja/open-funding/branches - `master` branch should be just removed if it was decided to spend effort on renaming master branch?
> 
> (I just run into confusing situation as result of having `main` in addition to `master`)

Aye. Fixing that now.

**Comment by ralphtheninja** [comment]
Done.
